# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_uploaded',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_name', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'pdf_uploaded',
            },
        ),
        migrations.CreateModel(
            name='registeruser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=4000)),
                ('user_email', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('user_password', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'db_table': 'register_user',
            },
        ),
    ]
